/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  IDatasetInfoApiTemporary,
  IDatasetInfoApiTemporaryInterface,
} from "../IDatasetInfoApiTemporary";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "url",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "abi_signature",
                    type: "string",
                  },
                ],
                internalType: "struct IDatasetInfoApi.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes",
                    name: "abi_encoded_data",
                    type: "bytes",
                  },
                ],
                internalType: "struct IDatasetInfoApi.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IDatasetInfoApi.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IDatasetInfoApi.Proof",
        name: "_proof",
        type: "tuple",
      },
    ],
    name: "proof",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "attestationType",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "sourceId",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "messageIntegrityCode",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "string",
                name: "url",
                type: "string",
              },
              {
                internalType: "string",
                name: "abi_signature",
                type: "string",
              },
            ],
            internalType: "struct IDatasetInfoApi.RequestBody",
            name: "requestBody",
            type: "tuple",
          },
        ],
        internalType: "struct IDatasetInfoApi.Request",
        name: "_request",
        type: "tuple",
      },
    ],
    name: "request",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "attestationType",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "sourceId",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "votingRound",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "lowestUsedTimestamp",
            type: "uint64",
          },
          {
            components: [
              {
                internalType: "string",
                name: "url",
                type: "string",
              },
              {
                internalType: "string",
                name: "abi_signature",
                type: "string",
              },
            ],
            internalType: "struct IDatasetInfoApi.RequestBody",
            name: "requestBody",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes",
                name: "abi_encoded_data",
                type: "bytes",
              },
            ],
            internalType: "struct IDatasetInfoApi.ResponseBody",
            name: "responseBody",
            type: "tuple",
          },
        ],
        internalType: "struct IDatasetInfoApi.Response",
        name: "_response",
        type: "tuple",
      },
    ],
    name: "response",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610163806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806314cf2b1e1461004657806371740054146100595780638077673a14610067575b600080fd5b610057610054366004610075565b50565b005b6100576100543660046100b7565b6100576100543660046100f2565b60006020828403121561008757600080fd5b813567ffffffffffffffff81111561009e57600080fd5b820160c081850312156100b057600080fd5b9392505050565b6000602082840312156100c957600080fd5b813567ffffffffffffffff8111156100e057600080fd5b8201608081850312156100b057600080fd5b60006020828403121561010457600080fd5b813567ffffffffffffffff81111561011b57600080fd5b8201604081850312156100b057600080fdfea264697066735822122086d08f91754502fae15a51d537e5dbf7bfc9f8d96f3627e5a8355db04a15ee2264736f6c63430008140033";

type IDatasetInfoApiTemporaryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IDatasetInfoApiTemporaryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class IDatasetInfoApiTemporary__factory extends ContractFactory {
  constructor(...args: IDatasetInfoApiTemporaryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      IDatasetInfoApiTemporary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): IDatasetInfoApiTemporary__factory {
    return super.connect(runner) as IDatasetInfoApiTemporary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IDatasetInfoApiTemporaryInterface {
    return new Interface(_abi) as IDatasetInfoApiTemporaryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDatasetInfoApiTemporary {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDatasetInfoApiTemporary;
  }
}
