/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDatasetInfoApiTemporary } from "./IDatasetInfoApiTemporary";
export * as factories from "./factories";
export { IDatasetInfoApiTemporary__factory } from "./factories/IDatasetInfoApiTemporary__factory";
